version: '3.8'

services:

  db:
    image: gitlab.area403.org:5050/j3/db:main
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=j3

  backend:
    build:
      context: ../j3-graphql
      dockerfile: ../j3-graphql/docker/server-gql/Dockerfile
    ports:
      - 5050:5050
    depends_on:
      - db
    environment:
      - GQL_POSTGRESQL_URL=postgres://bob:secret@db:5432/j3
