query ListDocuments($request: ListDocumentsRequest!) {
  listDocuments(request: $request) {
    documents {
      id,
      title,
      outline,
      content,
      html,
      tags,
      genre,
      createdAt,
      updatedAt
    },
    count
  }
}
